# Generated by Django 4.0.3 on 2022-05-25 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0006_post_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='cover',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
